server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: Ashu@123

  application:
    name: User Service

  jpa:
    hibernate:
      ddl-auto: update
